source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target "CompanyAPPStore" do
    pod 'Alamofire', '~> 4.0'
    pod 'SDWebImage', '~> 4.1.0'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'JPush'
end
